//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.8-b130911.1802 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2015.05.29 at 03:15:07 PM BST 
//
package de.atb.context.tools.ontology;

/*-
 * #%L
 * ATB Context Extraction Core Lib
 * %%
 * Copyright (C) 2020 ATB – Institut für angewandte Systemtechnik Bremen GmbH
 * %%
 * This program and the accompanying materials are made
 * available under the terms of the Eclipse Public License 2.0
 * which is available at https://www.eclipse.org/legal/epl-2.0/
 * 
 * SPDX-License-Identifier: EPL-2.0
 * #L%
 */


import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlType;
import java.util.ArrayList;
import java.util.List;

/**
 * <p>
 * Java class for Solution complex type.
 *
 * <p>
 * The following schema fragment specifies the expected content contained within
 * this class.
 *
 * <pre>
 * &lt;complexType name="Solution"&gt;
 *   &lt;complexContent&gt;
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType"&gt;
 *       &lt;sequence&gt;
 *         &lt;element name="Id" type="{http://www.w3.org/2001/XMLSchema}string"/&gt;
 *         &lt;element name="name" type="{http://www.w3.org/2001/XMLSchema}string"/&gt;
 *         &lt;element name="Creator" type="{http://www.w3.org/2001/XMLSchema}string"/&gt;
 *         &lt;element name="type" type="{http://www.w3.org/2001/XMLSchema}string"/&gt;
 *         &lt;element name="hasDefinitions" type="{http://xml.netbeans.org/schema/newXmlSchema}Definition" maxOccurs="unbounded"/&gt;
 *         &lt;element name="Creation_Date" type="{http://www.w3.org/2001/XMLSchema}string"/&gt;
 *         &lt;element name="Description" type="{http://www.w3.org/2001/XMLSchema}string"/&gt;
 *       &lt;/sequence&gt;
 *     &lt;/restriction&gt;
 *   &lt;/complexContent&gt;
 * &lt;/complexType&gt;
 * </pre>
 *
 *
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "Solution", propOrder = {"id", "name", "creator", "type",
    "hasDefinitions", "creationDate", "description", "product"})
public class Solution {

    @XmlElement(name = "Id", required = true)
    protected String id;
    @XmlElement(required = true)
    protected String name;
    @XmlElement(name = "Creator", required = true)
    protected String creator;
    @XmlElement(required = true)
    protected String type;
    @XmlElement(required = true)
    protected List<Definition> hasDefinitions;
    @XmlElement(name = "Creation_Date", required = true)
    protected String creationDate;
    @XmlElement(name = "Description", required = true)
    protected String description;
    @XmlElement(name = "Product", required = true)
    protected Product product;

    /**
     * Gets the value of the id property.
     *
     * @return possible object is {@link String }
     *
     */
    public final String getId() {
        return id;
    }

    /**
     * Sets the value of the id property.
     *
     * @param value allowed object is {@link String }
     *
     */
    public final void setId(final String value) {
        this.id = value;
    }

    /**
     * Gets the value of the name property.
     *
     * @return possible object is {@link String }
     *
     */
    public final String getName() {
        return name;
    }

    /**
     * Sets the value of the name property.
     *
     * @param value allowed object is {@link String }
     *
     */
    public final void setName(final String value) {
        this.name = value;
    }

    /**
     * Gets the value of the creator property.
     *
     * @return possible object is {@link String }
     *
     */
    public final String getCreator() {
        return creator;
    }

    /**
     * Sets the value of the creator property.
     *
     * @param value allowed object is {@link String }
     *
     */
    public final void setCreator(final String value) {
        this.creator = value;
    }

    /**
     * Gets the value of the type property.
     *
     * @return possible object is {@link String }
     *
     */
    public final String getType() {
        return type;
    }

    /**
     * Sets the value of the type property.
     *
     * @param value allowed object is {@link String }
     *
     */
    public final void setType(final String value) {
        this.type = value;
    }

    /**
     * Gets the value of the hasDefinitions property.
     *
     * <p>
     * This accessor method returns a reference to the live list, not a
     * snapshot. Therefore any modification you make to the returned list will
     * be present inside the JAXB object. This is why there is not a
     * <CODE>set</CODE> method for the hasDefinitions property.
     *
     * <p>
     * For example, to add a new item, do as follows:
     *
     * <pre>
     * getHasDefinitions().add(newItem);
     * </pre>
     *
     *
     * <p>
     * Objects of the following type(s) are allowed in the list
	 * {@link Definition }
     *
     * @return list of Definition objects
     *
     *
     */
    public final List<Definition> getHasDefinitions() {
        if (hasDefinitions == null) {
            hasDefinitions = new ArrayList<>();
        }
        return this.hasDefinitions;
    }

    /**
     * Gets the value of the creationDate property.
     *
     * @return possible object is {@link String }
     *
     */
    public final String getCreationDate() {
        return creationDate;
    }

    /**
     * Sets the value of the creationDate property.
     *
     * @param value allowed object is {@link String }
     *
     */
    public final void setCreationDate(final String value) {
        this.creationDate = value;
    }

    /**
     * Gets the value of the description property.
     *
     * @return possible object is {@link String }
     *
     */
    public final String getDescription() {
        return description;
    }

    /**
     * Sets the value of the description property.
     *
     * @param value allowed object is {@link String }
     *
     */
    public final void setDescription(final String value) {
        this.description = value;
    }

    public Product getProduct() {
        return product;
    }

    public void setProduct(Product product) {
        this.product = product;
    }

}
