#!/bin/sh
#./dashAnalysis.sh "Maven" "smartclide-api-gateway"
#./dashAnalysis.sh "Maven" "smartclide-broker"
#./dashAnalysis.sh "Maven" "smartclide-cicd"
#./dashAnalysis.sh "Maven" "smartclide-context"
./dashAnalysis.sh "Maven" "smartclide-security/Theia-BackEnd" "smartclide-security"
#./dashAnalysis.sh "Maven" "smartclide-service-creation"
#./dashAnalysis.sh "Maven" "smartclide-TD-Interest"
#./dashAnalysis.sh "Maven" "smartclide-TD-Reusability-Index"
#./dashAnalysis.sh "Maven" "smartclide-TD-Principal"
#./dashAnalysis.sh "Nodes" "smartclide-ide-front-end"
#./dashAnalysis.sh "Nodes" "smartclide-perftestgen-theia"
#./dashAnalysis.sh "Yarn" "smartclide-service-creation-theia"
#./dashAnalysis.sh "Yarn" "smartclide-td-reusability-theia"
#./dashAnalysis.sh "Yarn" "smartclide-design-pattern-selection-theia"
